# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tyt 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "tyt"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Timmy Crawford"]
  s.date = "2013-12-03"
  s.description = "Track Your Turns (tyt) provides a wrapper to ski area turn tracking data sets"
  s.email = "timmydcrawford@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/tyt.rb",
    "lib/tyt/bachelor.rb",
    "lib/tyt/run_detail.rb",
    "lib/tyt/season.rb",
    "lib/tyt/ski_day.rb",
    "test/cassettes/04-13-13_date_page.yml",
    "test/cassettes/04-14-13_date_page.yml",
    "test/cassettes/12_13_season_page.yml",
    "test/cassettes/13_14_season_page.yml",
    "test/helper.rb",
    "test/test_bachelor.rb",
    "test/test_run_detail.rb",
    "test/test_season.rb",
    "test/test_ski_day.rb",
    "tyt.gemspec"
  ]
  s.homepage = "http://github.com/timmyc/tyt"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "A wrapper for accessing vertical turn tracking information from ski areas"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
  end
end

